//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Navettes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonne_abonnement
    {
        public int id { get; set; }
        public Nullable<int> id_abonne { get; set; }
        public Nullable<int> id_abonnement { get; set; }
    
        public virtual abonne abonne { get; set; }
        public virtual abonnement abonnement { get; set; }
    }
}
