//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Navettes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public abonnement()
        {
            this.abonne_abonnement = new HashSet<abonne_abonnement>();
        }
    
        public int id { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin { get; set; }
        public System.TimeSpan heure_depart { get; set; }
        public System.TimeSpan heure_arrivee { get; set; }
        public int nbr_abonne_voulu { get; set; }
        public decimal prix_abonnement { get; set; }
        public Nullable<int> id_autocar { get; set; }
        public Nullable<int> id_ville_depart { get; set; }
        public Nullable<int> id_ville_arrivee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<abonne_abonnement> abonne_abonnement { get; set; }
        public virtual autocar autocar { get; set; }
        public virtual ville ville { get; set; }
        public virtual ville ville1 { get; set; }
    }
}
